CREATE TABLE [dbo].[Cust_Status](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Status] [nvarchar](256) NOT NULL,
	[NormalizedStatus] [nvarchar](256) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO